export const items = [
    {
        "cod_art": "1",
        "name": "ESPECIAL DE LA CASA",
        "category": "BOCADILLOS",
        "tax": 10,
        "pvp_without_tax": 5.45,
        "pvp": 6,
    },
    {
        "cod_art": "2",
        "name": "BLANCO Y NEGRO",
        "category": "BOCADILLOS",
        "tax": 10,
        "pvp_without_tax": 5.45,
        "pvp": 6,
    },
    {
        "cod_art": "3",
        "name": "ALMUSSAFES",
        "category": "BOCADILLOS",
        "tax": 10,
        "pvp_without_tax": 5.45,
        "pvp": 6,
    },
    {
        "cod_art": "4",
        "name": "XIMO",
        "category": "BOCADILLOS",
        "tax": 10,
        "pvp_without_tax": 5.45,
        "pvp": 6,
    },
    {
        "cod_art": "5",
        "name": "SERRANITO",
        "category": "BOCADILLOS",
        "tax": 10,
        "pvp_without_tax": 5.45,
        "pvp": 6,
    },
    {
        "cod_art": "6",
        "name": "VEGETAL",
        "category": "BOCADILLOS",
        "tax": 10,
        "pvp_without_tax": 5.45,
        "pvp": 6,
    },
    {
        "cod_art": "7",
        "name": "CHIVITO",
        "category": "BOCADILLOS ESPECIALES",
        "tax": 10,
        "pvp_without_tax": 6.36,
        "pvp": 7,
    },
    {
        "cod_art": "8",
        "name": "BRASCADA",
        "category": "BOCADILLOS ESPECIALES",
        "tax": 10,
        "pvp_without_tax": 6.36,
        "pvp": 7,
    },
    {
        "cod_art": "9",
        "name": "FULL",
        "category": "BOCADILLOS ESPECIALES",
        "tax": 10,
        "pvp_without_tax": 6.36,
        "pvp": 7,
    },
    {
        "cod_art": "1B",
        "name": "COCA COLA",
        "category": "REFRESCOS",
        "tax": 10,
        "pvp_without_tax": 2.25,
        "pvp": 2.5,
    },
    {
        "cod_art": "2B",
        "name": "COCA COLA ZERO",
        "category": "REFRESCOS",
        "tax": 10,
        "pvp_without_tax": 2.25,
        "pvp": 2.5,
    },
    {
        "cod_art": "3B",
        "name": "COCA COLA ZERO ZERO",
        "category": "REFRESCOS",
        "tax": 10,
        "pvp_without_tax": 2.25,
        "pvp": 2.5,
    },
    {
        "cod_art": "4B",
        "name": "FANTA NARANJA",
        "category": "REFRESCOS",
        "tax": 10,
        "pvp_without_tax": 2.25,
        "pvp": 2.5,
    },
    {
        "cod_art": "5B",
        "name": "SPRITE",
        "category": "REFRESCOS",
        "tax": 10,
        "pvp_without_tax": 2.25,
        "pvp": 2.5,
    },
    {
        "cod_art": "6B",
        "name": "AQUARIUS",
        "category": "REFRESCOS",
        "tax": 10,
        "pvp_without_tax": 2.25,
        "pvp": 2.5,
    },
    {
        "cod_art": "1A",
        "name": "AGUA GRANDE",
        "category": "AGUAS Y ZUMOS",
        "tax": 10,
        "pvp_without_tax": 2.05,
        "pvp": 2.25,
    },
    {
        "cod_art": "2A",
        "name": "AGUA PEQUEÑA",
        "category": "AGUAS Y ZUMOS",
        "tax": 10,
        "pvp_without_tax": 1.73,
        "pvp": 1.90,
    },
    {
        "cod_art": "3A",
        "name": "ZUMO NARANJA",
        "category": "AGUAS Y ZUMOS",
        "tax": 10,
        "pvp_without_tax": 2.14,
        "pvp": 2.35,
    },
    {
        "cod_art": "1D",
        "name": "AMSTEL",
        "category": "CERVEZAS",
        "tax": 10,
        "pvp_without_tax": 2.14,
        "pvp": 2.35,
    },
    {
        "cod_art": "2D",
        "name": "ESTRELLA GALICIA",
        "category": "CERVEZAS",
        "tax": 10,
        "pvp_without_tax": 2.14,
        "pvp": 2.35,
    },
    {
        "cod_art": "3D",
        "name": "AMSTEL 1L",
        "category": "CERVEZAS",
        "tax": 10,
        "pvp_without_tax": 3.64,
        "pvp": 4,
    },
    {
        "cod_art": "1C",
        "name": "CAFÉ SOLO",
        "category": "CAFÉS E INFUSIONES",
        "tax": 10,
        "pvp_without_tax": 1.27,
        "pvp": 1.4,
    },
    {
        "cod_art": "2C",
        "name": "CORTADO",
        "category": "CAFÉS E INFUSIONES",
        "tax": 10,
        "pvp_without_tax": 1.36,
        "pvp": 1.5,
    },
    {
        "cod_art": "3C",
        "name": "CAFÉ CON LECHE",
        "category": "CAFÉS E INFUSIONES",
        "tax": 10,
        "pvp_without_tax": 1.46,
        "pvp": 1.6,
    },
    {
        "cod_art": "4C",
        "name": "MANZANILLA",
        "category": "CAFÉS E INFUSIONES",
        "tax": 10,
        "pvp_without_tax": 1.27,
        "pvp": 1.4,
    },
    {
        "cod_art": "5C",
        "name": "TIMONET",
        "category": "CAFÉS E INFUSIONES",
        "tax": 10,
        "pvp_without_tax": 1.27,
        "pvp": 1.4,
    },

]

export const taxes = [
    {
        "value": 21, // IVA 21%
    },
    {
        "value": 10, // IVA 10%
    },
    {
        "value": 4, // IVA 4%
    },
    {
        "value": 0, // IVA 0%
    },
]